image: debian:latest

on:
  push:
    branches:
      - main

jobs:
  before_script:
    - apt-get update -qq -y
    - apt-get install -y hlint

  lint:
    script:
      - hlint src/*.hs app/*.hs test/*.hs

  # artifacts:
  #  paths:
  #    - public

  # rules:
  #  - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
